version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: password
    

  web:
    build: .
    depends_on:
      - webpack-dev-server
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack-dev-server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/omusubi
      - /omusubi/node_modules
    ports:
      - "3000:3000"
      - "9443:9443"
    depends_on:
      - db

  webpack-dev-server:
    build: .
    command: /omusubi/bin/webpack-dev-server
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - 3035:3035
    volumes:
      - .:/omusubi
      - /omusubi/node_modules

volumes:
  postgresql-data:
    driver: local